[[post]]
category = "Python Programming"
title = "Pieran Data Complete Python Bootcamp"
#subtitle = ""
datetime = "2022-10-27"
image = "config/assets/posts/udemy.png"
url = "https://drive.google.com/drive/u/0/folders/1VREtpDBFp6TLyiQ7SZ3y6tYnFivegWRp"

[[post]]
category = "Data Analytics"
title = "Google Data Analytics Professional Certificate"
#subtitle = ""
datetime = "2023-03-05"
image = "config/assets/posts/Coursera.png"
url = "https://drive.google.com/drive/folders/1wmpmPGGlZbw8J1MBTtVMloAnTq3iG3oA?usp=sharing"

[[post]]
category = "Design"
title = "Design digest #80"
subtitle = "Excepteur sint occaecat cupidatat no proident, quis nostrum exercitationem ullam corporis suscipit"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-3.jpg"
url = "https://hashnode.com"

[[post]]
category = "Design"
title = "UI interactions of the week"
subtitle = "Enim ad minim veniam, consectetur adipiscing elit, quis nostrud exercitation ullamco laboris nisi"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-4.jpg"
url = "https://dev.to"

[[post]]
category = "Design"
title = "The Forgotten Art Of Spacing"
subtitle = "Maxime placeat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-5.jpg"
url = "https://medium.com"

[[post]]
category = "Design"
title = "Design Digest #79"
subtitle = "Optio cumque nihil impedit uo minus quod maxime placeat, velit esse cillum"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-6.jpg"
url = "https://hashnode.com"
