[[doing]]
title = "Data Analysis"
icon = "./config/assets/icons/DataAnalysis.svg"
text = "Unlocking insights from raw data to drive strategic decisions"

[[doing]]
title = "Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using Python to enhance efficiency and productivity."

[[doing]]
title = "Data Visualization"
icon = "./config/assets/icons/compass.svg"
text = "Intuitive and visually appealing user interfaces and user experiences."

# [[doing]]
# title = "Web Development"
# icon = "./config/assets/icons/laptop-code.svg"
# text = "High-quality development of sites at the professional level."
