[[project]]
title = "Telecom Churn Analysis"
category = "Data Analytics"
image = "https://imgur.com/FPFlTvx.png"
url = "https://github.com/Sammy-Lartey/Telecom-Customer-Churn"

[[project]]
title = "Chips Sales Analysis (QUANTIUM Virtual Experience Program)"
category = "Data Analytics"
image = "config/assets/projects/Chips.jpg"
url = "https://github.com/Sammy-Lartey/QUANTIUM-Data-Analytics-Virtual-Experience-Program"

[[project]]
title = "Flutter Todo App"
category = "Mobile development"
image = "https://imgur.com/7110Lj1.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Flutter Travel News App"
category = "Mobile development"
image = "https://imgur.com/t5T5Ixa.png"
url = "https://github.com/ivansaul/flutter_travel_news_app#screenshots"

[[project]]
title = "Codigo Facilito Downloader"
category = "Python Programming"
image = "https://imgur.com/kyHrBGk.png"
url = "https://github.com/ivansaul/codigo_facilito_downloader"

[[project]]
title = "Bike Store Dashboard"
category = "Data Visualization"
image = "./config/assets/projects/Viz 1.png"
url = "https://public.tableau.com/app/profile/sammy.lartey/viz/BikeStoreDashboard_16920594543270/Dashboard1"

[[project]]
title = "IMDB Dashboard"
category = "Data Visualization"
image = "./config/assets/projects/Viz 2.png"
url = "https://public.tableau.com/app/profile/sammy.lartey/viz/IMDBDashboard_16898211927910/Dashboard1"

[[project]]
title = "Fundo"
category = "Web design"
image = "./config/assets/projects/project-3.jpg"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

[[project]]
title = "Brawlhalla"
category = "Applications"
image = "./config/assets/projects/project-4.png"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "DSM."
category = "Web design"
image = "./config/assets/projects/project-5.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "MetaSpark"
category = "Web design"
image = "./config/assets/projects/project-6.png"
url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "Summary"
category = "Web development"
image = "./config/assets/projects/project-7.png"
url = "https://github.com/ivansaul/codigo_facilito_downloader"

[[project]]
title = "Task Manager"
category = "Applications"
image = "./config/assets/projects/project-8.jpg"
url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

[[project]]
title = "Arrival"
category = "Web development"
image = "./config/assets/projects/project-9.png"
url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"
