############## Education config #################
#################################################
[[education]]
title = "Pieran Data Python Programming Bootcamp"
timeline = "October 2022 - December 2022"
description = """
Coursework: Python Basics, Object Oriented Programming in Python, Databases with Python, Advanced Python Modules, 
Python for Data Science and Machine Learning.
"""

[[education]]
title = "Google Data Analytics Professional Certificate"
timeline = "January 2023 - April 2023"
description = """
Coursework: Intro to Data Analytics, Advanced data cleaning, Data analysis with Google Sheets and Microsoft Excel, Data 
analysis with SQL and R programming, Data Visualization with Tableau.
"""

[[education]]
title = "QUANTIUM Data Analytics Virtual Experience Program"
timeline = "March 2024"
description = """
Data preparation and customer analytics, Experimentation and uplift testing Analytics and commercial application using Python 
programming.
"""

[[education]]
title = "Bachelor of Science in Computer Science"
school = "Catholic University College of Ghana"
timeline = "September 2017 — October 2021"
description = """
Relevant Coursework: Data Structures and Algorithms, Critical Thinking, Database Management Systems, Statistical Analysis,
Object Oriented Programming, Data Science and Machine Learning.
"""


############## Experience config ################
#################################################
[[experience]]
title = "Web designer"
timeline = "2010 — 2013"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Art director"
timeline = "2013 — 2015"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Creative director"
timeline = "2015 — Present"
description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Web design"
value = "80%"

[[skill]]
title = "Graphic design"
value = "70%"

[[skill]]
title = "Branding"
value = "90%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Ingles"
value = "60%"

[[language]]
title = "French"
value = "50%"
