############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "Adaptability"
icon = "./config/assets/icons/bolt.svg"
text = "I am flexible and open to change, able to thrive in dynamic environments and navigate challenges with resilience."

[[skills]]
title = "Teamwork"
icon = "./config/assets/icons/user.svg"
text = "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."

[[skills]]
title = "Problem Solving"
icon = "./config/assets/icons/gear.svg"
text = "I am creative and efficient in identifying and solving technical problems."

[[skills]]
title = "Communication"
icon = "./config/assets/icons/comment.svg"
text = "I am proficient in articulating ideas and concepts clearly and effectively, whether in written or verbal form."
