############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "Adaptable"
icon = "./config/assets/icons/bolt.svg"
text = "I quickly adjust to any new project requirements and am always eager to learn. I enjoy stepping out of my comfort zone to embrace new technologies and methodologies with enthusiasm, ensuring I stay ahead of the curve."

[[skills]]
title = "Teamwork"
icon = "./config/assets/icons/user.svg"
text = "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."

[[skills]]
title = "Problem Solving"
icon = "./config/assets/icons/gear.svg"
text = "i excel in problem-solving by meticulously analyzing challenges and breaking them down into manageable components."

[[skills]]
title = "Effective Communication"
icon = "./config/assets/icons/comment.svg"
text = "I am proficient in articulating ideas and concepts clearly and effectively, whether in written or verbal form."
